"""Thermal / dark-current noise — Ch. 1, Ch. 8."""

import cv2
import numpy as np

from .base import Noise


class ThermalNoise(Noise):
    """False charge generated by heat; most prominent in dark regions.

    Noise model: approximately Gaussian, additive, concentrated in low-
    intensity areas.

    Detection: measures the noise standard deviation exclusively within dark
    pixels (below *dark_threshold*).  Elevated noise there while the overall
    image is dark signals thermal / dark-current contamination.

    Removal: Gaussian denoising applied only within the dark region; bright
    areas are left untouched to preserve highlights.
    """

    def __init__(
        self,
        dark_threshold: int = 50,
        sigma_threshold: float = 4.0,
        gauss_ksize: int = 5,
    ) -> None:
        self._dark_threshold = dark_threshold
        self._sigma_threshold = sigma_threshold
        self._gauss_ksize = gauss_ksize

    @property
    def name(self) -> str:
        return "Thermal / Dark-Current Noise"

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _dark_sigma(self, gray: np.ndarray) -> float:
        dark_pixels = gray[gray < self._dark_threshold].astype(np.float32)
        if dark_pixels.size < 64:
            return 0.0
        return float(np.std(dark_pixels))

    # ------------------------------------------------------------------
    # Interface
    # ------------------------------------------------------------------

    def detect(self, frame: np.ndarray) -> bool:
        gray = (
            cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) if frame.ndim == 3 else frame
        )
        return self._dark_sigma(gray) > self._sigma_threshold

    def remove(self, frame: np.ndarray) -> np.ndarray:
        gray = (
            cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) if frame.ndim == 3 else frame
        )
        dark_mask = gray < self._dark_threshold
        result = frame.copy().astype(np.float32)
        ks = self._gauss_ksize
        blurred = cv2.GaussianBlur(result, (ks, ks), 0)
        if frame.ndim == 3:
            mask3 = np.stack([dark_mask] * 3, axis=-1)
            result[mask3] = blurred[mask3]
        else:
            result[dark_mask] = blurred[dark_mask]
        return np.clip(result, 0, 255).astype(np.uint8)
